apiVersion: v2
name: otel-demo
version: 0.1.0
dependencies:
  - name: opentelemetry-demo
    version: 0.25.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: opentelemetry-collector
    version: 0.94.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: kube-state-metrics
    version: 5.14.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: traefik
    version: 28.0.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
