domain: ""
ingress:
  class: gce
  staticIpName: ""
services:
  app: opentelemetry-demo-frontendproxy
  grafana: opentelemetry-demo-grafana
  prometheus: opentelemetry-demo-prometheus-server
  jaeger: opentelemetry-demo-jaeger-query
  opensearch: opentelemetry-demo-opensearch

opentelemetry-demo:
  components:
    grafana:
      enabled: true
    prometheus:
      enabled: true
    jaeger:
      enabled: true
    opensearch:
      enabled: true

opentelemetry-collector:
  mode: daemonset
  config: |
    receivers:
      kubeletstats:
        collection_interval: 10s
      hostmetrics:
        collection_interval: 10s
      prometheus:
        config:
          scrape_configs:
            - job_name: ksm
              static_configs:
                - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
    processors:
      batch: {}
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
      logging: {}
    service:
      pipelines:
        metrics:
          receivers: [kubeletstats, hostmetrics, prometheus]
          processors: [batch]
          exporters: [prometheus, logging]

kube-state-metrics:
  releaseNamespace: kube-system

traefik:
  enabled: false
