domain: ""
ingress:
  class: gce
  staticIpName: ""
services:
  app: opentelemetry-demo-frontendproxy
  grafana: opentelemetry-demo-grafana
  prometheus: opentelemetry-demo-prometheus-server
  jaeger: opentelemetry-demo-jaeger-query
  opensearch: opentelemetry-demo-opensearch

opentelemetry-collector:
  mode: "daemonset"
  image:
    repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
  presets:
    kubernetesAttributes:
      enabled: true
    kubeletMetrics:
      enabled: true
    hostMetrics:
      enabled: true
    logsCollection:
      enabled: true
      includeCollectorLogs: false
      storeCheckpoints: true

kube-state-metrics:
  releaseNamespace: kube-system

traefik:
  enabled: false
